name: Release

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'

env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.14.0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.32.1

      - run: pnpm install --frozen-lockfile
      - run: pnpm check-types
      - run: pnpm lint
      - run: pnpm test:unit
      - run: pnpm test:integration

  release:
    name: Release
    needs: [validate]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version: 24.14.0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.32.1

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: Release
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
